### ISSUE TITLE
APS Docker Compose file for Hyland Univeristy

### ISSUE THREAD

**Issue by WFindley0** [aborroy/aps-docker-deployment#1]
I'm needing a new compose file similar to the one below. The volumes listed in the code already should suffice, with versioning needing to be latest, or 24.2.0 for APS and similar compatibility for other services. 

If possible, could you leave comments to explain areas that have changed? Not a big need, but always nice. 

`

#Alfresco University

#Using version 2 as 3 does not support resource constraint options (cpu_*, mem_* limits) for non swarm mode in Compose
#version: "2"

services:
    process:
        platform: linux/amd64
        image: alfresco/process-services:24.2.0
        environment:
            ACTIVITI_DATASOURCE_USERNAME: alfresco
            ACTIVITI_DATASOURCE_PASSWORD: alfresco
            ACTIVITI_DATASOURCE_DRIVER: org.postgresql.Driver
            ACTIVITI_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
            ACTIVITI_DATASOURCE_URL: 'jdbc:postgresql://postgres-aps:5432/activiti?characterEncoding=UTF-8'
            ACTIVITI_CSRF_DISABLED: 'true'
            ACTIVITI_CORS_ENABLED: 'true'
            ACTIVITI_ES_SERVER_TYPE: rest
            ACTIVITI_ES_REST_CLIENT_ADDRESS: elasticsearch
            ACTIVITI_ES_REST_CLIENT_PORT: 9200
            ACTIVITI_ES_REST_CLIENT_SCHEMA: http
        ports:
            - 8180:8080
        depends_on:
            - postgres-aps

        

    process-admin:
        platform: linux/amd64
        image: alfresco/process-services-admin:24.2.0
        ports:
            - 8181:8080
        depends_on:
            - postgres-aps-admin
            - process
        volumes:
            - ./activiti-admin.properties:/usr/local/tomcat/lib/activiti-admin.properties
        

    elasticsearch:
        platform: linux/amd64
        image: elasticsearch:7.10.1
        environment:
            - xpack.security.enabled=false
            - discovery.type=single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        cap_add:
            - IPC_LOCK
        ports:
            - 9200:9200
            - 9300:9300

    postgres-aps:
        platform: linux/amd64
        image: postgres:11.6
        environment:
            POSTGRES_DB: activiti
            POSTGRES_USER: alfresco
            POSTGRES_PASSWORD: alfresco
        

    postgres-aps-admin:
        platform: linux/amd64
        image: postgres:11.6
        environment:
            POSTGRES_DB: activiti_admin
            POSTGRES_USER: alfresco
            POSTGRES_PASSWORD: alfresco
        volumes:
            - "$ALFU/license/aps:/root/.activiti/enterprise-license:ro"`

**Comment by aborroy** [comment]
Repository has been updated with support for APS 24 and AARCH64 (Apple with Silicon chip).

Main differences are:

1. **Environment Variables and Image Versions**:
   - Uses environment variables for image and tag definitions (`${PROCESS_SERVICES_IMAGE}`, `${PROCESS_SERVICES_TAG}`, `${PROCESS_SERVICES_ADMIN_IMAGE}`, `${PROCESS_SERVICES_ADMIN_TAG}`, `${ELASTICSEARCH_TAG}`, `${POSTGRES_TAG}`).
   - Allows for dynamic configuration of images and versions.

2. **Service Definitions**:

   - **Process**:
     - **Image**: Uses variables for image and tag.
     - **Ports**: `9090:8080` (different from `8180:8080` in the first file).
     - **Additional Environment Variable**: `JAVA_OPTS` for JVM memory settings.
     - **Depends On**: Includes health checks for dependencies (`postgres-aps` and `elasticsearch`).
     - **Volumes**: Mounts license file and a named volume `aps-contentstore-volume` for persistent storage.

   - **Process-Admin**:
     - **Image**: Uses variables for image and tag.
     - **Ports**: `9091:8080` (different from `8181:8080` in the first file).
     - **Additional Environment Variable**: `JAVA_OPTS` for JVM memory settings.
     - **Depends On**: Includes health check for `postgres-aps-admin`.

   - **Elasticsearch**:
     - **Image**: Uses a variable for the tag.
     - **Container Name**: Explicitly named `elasticsearch`.
     - **Additional Environment Variable**: `ES_JAVA_OPTS` for JVM memory settings.
     - **Healthcheck**: Added health check configuration to verify service readiness.
     - **Volumes**: Uses a named volume `aps-es-volume` for persistent storage.

   - **Postgres-APS**:
     - **Image**: Uses a variable for the tag.
     - **Command**: Configures Postgres with `max_connections` and `log_min_messages`.
     - **Healthcheck**: Added health check configuration to verify service readiness.
     - **Volumes**: Uses a named volume `aps-db-volume` for persistent storage.

   - **Postgres-APS-Admin**:
     - **Image**: Uses a variable for the tag.
     - **Command**: Configures Postgres with `max_connections` and `log_min_messages`.
     - **Healthcheck**: Added health check configuration to verify service readiness.
     - **Volumes**: Uses a named volume `aps-admin-db-volume` for persistent storage.

3. **Resource Constraints and Configuration**:
   - Both configurations use `ulimits` and `cap_add` for `elasticsearch`, but the second configuration adds JVM options for memory management (`JAVA_OPTS` and `ES_JAVA_OPTS`).

4. **Volume Definitions**:
   - Named volumes are explicitly defined at the bottom of the second configuration:
     - `aps-db-volume`
     - `aps-admin-db-volume`
     - `aps-contentstore-volume`
     - `aps-es-volume`
   - These named volumes ensure persistent storage across container restarts.

5. **Health Checks**:
   - The second configuration includes health checks for `elasticsearch`, `postgres-aps`, and `postgres-aps-admin`, ensuring that dependent services wait until these services are fully ready before starting.

6. **Port Mappings**:
   - Ports are mapped differently, potentially to avoid conflicts and for easier access:
     - `process` on `9090:8080` instead of `8180:8080`.
     - `process-admin` on `9091:8080` instead of `8181:8080`.
