### ISSUE TITLE
AARCH64 Exit Code 

### ISSUE THREAD

**Issue by WFindley0** [aborroy/aps-docker-deployment#2]
When building aarch64 images for Activiti and Admin apps, I'm experiencing an issue with the alfresco-base-tomcat Docker image. A quick fix was created by using an older version - here are my logs for the issue: 

`[+] Building 1.8s (14/21)                    docker-container:buildx-multi-arch
 => [internal] booting buildkit                                            1.1s
 => => pulling image moby/buildkit:buildx-stable-1                         0.7s
 => => creating container buildx_buildkit_buildx-multi-arch0               0.5s
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 1.96kB                                     0.0s
 => WARN: StageNameCasing: Stage name 'APS' should be lowercase (line 2)   0.0s
 => WARN: InvalidDefaultArgInFrom: Default value for ARG alfresco/process  0.0s
 => [internal] load metadata for docker.io/alfresco/alfresco-base-tomcat:  0.4s
 => [internal] load metadata for docker.io/alfresco/process-services:24.2  0.4s
 => [auth] alfresco/alfresco-base-tomcat:pull token for registry-1.docker  0.0s
 => [auth] alfresco/process-services:pull token for registry-1.docker.io   0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => CACHED [stage-1  1/13] FROM docker.io/alfresco/alfresco-base-tomcat:t  0.0s
 => => resolve docker.io/alfresco/alfresco-base-tomcat:tomcat10-jre17-roc  0.0s
 => [aps 1/1] FROM docker.io/alfresco/process-services:24.2.0@sha256:98c1  0.1s
 => => resolve docker.io/alfresco/process-services:24.2.0@sha256:98c1e54f  0.0s
 => => sha256:20defe970a8436f5b0693d7dde6bb4bc60bdba59b5dde 0B / 332.10MB  0.1s
 => => sha256:cacfe55125905409019aff6215a017d27c4580a946eb0 0B / 319.58MB  0.1s
 => => sha256:ba2657833c3bbeb87f1ec60b2059ccfa97bff3055304211 0B / 1.93kB  0.0s
 => => sha256:56d57c7477694281fa1c6849a760c8772ca756f87733088 0B / 1.01kB  0.0s
 => ERROR [stage-1  2/13] RUN set -x    && useradd         -c "Alfresco A  0.1s
 => CANCELED [stage-1  3/13] COPY --from=APS /home/alfresco/ /home/alfres  0.0s
 => CANCELED [stage-1  4/13] COPY --from=APS /usr/local/tomcat/lib/activi  0.0s
 => CANCELED [stage-1  5/13] COPY --from=APS /usr/local/tomcat/lib/activi  0.0s
 => CANCELED [stage-1  6/13] COPY --from=APS /usr/local/tomcat/webapps/ /  0.0s
------
 > [stage-1  2/13] RUN set -x    && useradd         -c "Alfresco APS"         -M         -s "/bin/bash"         -u "33007"         -o         "alfresco"    && yum update -y    && yum install -y       unzip       wget       openssl       fontconfig dejavu-sans-fonts:
0.055 + useradd -c 'Alfresco APS' -M -s /bin/bash -u 33007 -o alfresco
0.080 useradd: Permission denied.
0.080 useradd: cannot lock /etc/passwd; try again later.
------

 5 warnings found (use --debug to expand):
 - StageNameCasing: Stage name 'APS' should be lowercase (line 2)
 - InvalidDefaultArgInFrom: Default value for ARG alfresco/process-services:${PROCESS_SERVICES_VERSION} results in empty or invalid base image name (line 2)
 - InvalidBaseImagePlatform: Base image alfresco/process-services:24.2.0 was pulled with platform "linux/amd64", expected "linux/arm64" for current build (line 2)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 23)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 24)
Dockerfile:8
--------------------
   7 |     
   8 | >>> RUN set -x \
   9 | >>>    && useradd \
  10 | >>>         -c "Alfresco APS" \
  11 | >>>         -M \
  12 | >>>         -s "/bin/bash" \
  13 | >>>         -u "${USERID}" \
  14 | >>>         -o \
  15 | >>>         "${USERNAME}" \
  16 | >>>    && yum update -y \
  17 | >>>    && yum install -y \
  18 | >>>       unzip \
  19 | >>>       wget \
  20 | >>>       openssl \
  21 | >>>       fontconfig dejavu-sans-fonts
  22 |     
--------------------
ERROR: failed to solve: process "/bin/bash -euo pipefail -c set -x    && useradd         -c \"Alfresco APS\"         -M         -s \"/bin/bash\"         -u \"${USERID}\"         -o         \"${USERNAME}\"    && yum update -y    && yum install -y       unzip       wget       openssl       fontconfig dejavu-sans-fonts" did not complete successfully: exit code: 1`

**Comment by aborroy** [comment]
n the latest version of the alfresco-base-tomcat image, root user access is no longer included by default:
https://github.com/Alfresco/alfresco-docker-base-tomcat/pull/169

For custom Docker images based on this version, you'll need to explicitly add the USER root directive before any commands that require root privileges.
